name: Flutter Admin CI

on:
  push:
    paths:
      - "mobile-admin/**"
  pull_request:

jobs:
  flutter-admin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - run: flutter pub get
        working-directory: mobile-admin

      - run: flutter analyze
        working-directory: mobile-admin

      - run: flutter test
        working-directory: mobile-admin
