name: Frontend CI

on:
  push:
    paths:
      - "legacy-frontend/**"
  pull_request:

jobs:
  html-css-js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7

      - name: Lint JS
        uses: reviewdog/action-eslint@v1
        with:
          workdir: legacy-frontend
          eslint_flags: "**/*.js"
